version: '3'

services:
  app:
    build: ./app
    volumes:
      - ./app/static:/app/static
    ports:
      - 8000:8000
    networks:
      - app-net
    command: gunicorn -w 4 -b 0.0.0.0:8000 'app:app'

  nginx:
    build: ./nginx
    volumes:
      - ./app/static:/app/static
    depends_on:
      - app
    networks:
      - app-net
    ports:
      - 82:82

volumes:
  static:


networks:
  app-net:
