name: GitHub Actions
on: [push]

jobs:
  Check-If-App-Running:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > app/.env
      - run: echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> app/.env
      - run: echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> app/.env
      - run: echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> app/.env
      - run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY}}" >> app/.env

      - name: Checkout .env file
        run: cat app/.env

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose
      
      - name: Build Docker Compose
        run: docker compose build

      - name: Run Docker Compose
        run: |
          docker compose up -d
          sleep 10

      - name: Get response from the server
        run: curl -I http://localhost:82

      - name: Stop Docker Compose
        run: docker compose down

      - name: Check if everything is working
        if: ${{ success() }}
        run: echo "Everything works fine!"

      - name: Report failure
        if: ${{ failure() }}
        run: echo "One or more containers exited with error code."
