name: GitHub Actions
on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  Check-If-App-Running:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout environment secrets
        run: echo "${{ secrets.REDIRECT_URI }}"

      - name: list the app directory
        run: ls app -a

      - name: Create the .env file
        run: |
          echo "SECRET_KEY: $SECRET_KEY >> app/.env"
          echo "CLIENT_ID: $CLIENT_ID >> app/.env"
          echo "CLIENT_SECRET: $CLIENT_SECRET >> app/.env"
          echo "REDIRECT_URI: $REDIRECT_URI >> app/.env"
          echo "GOOGLE_API_KEY: $GOOGLE_API_KEY >> app/.env"

      - name: List app directory again
        run: ls app -a

      # - name: Install Docker Compose
      #   run: sudo apt-get install docker-compose

      # - name: See what's in the .env file
      #   run: cat app/.env
      
      # - name: Build and run Docker Compose
      #   run: docker compose up --build --abort-on-container-exit

      # - name: Check if everything is working
      #   if: ${{ success() }}
      #   run: echo "All containers are running!"

      # - name: Report failure
      #   if: ${{ failure() }}
      #   run: echo "One or more containers exited with error code."
